### PR TITLE
chore: modify product description

### PR DESCRIPTION
**Pull request by solmyrcan**
# Description

This PR includes some modifications to the description text for Charmed Aether SD-Core, and some minor text modifications as proposed improvements.

# Checklist:

- [ x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [x ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

### CODE REVIEW

**Comment by markbeierl** [comment]
But it looks like your commits were not signed. We will have to go back and sign them.

**Review by gruyaume — CHANGES_REQUESTED** [review]
- Please update the PR title (which will end up being the commit message) so that it reflects what the update is. `doc update` is too generic and can be applied to any change in this project. Also, no need to place the Jira ticket id. 
- Please sign your commits

**Review by gruyaume — CHANGES_REQUESTED** [review]
There are still many unsigned commits will prevent merging this. Please either sign the old commits or squash them into a new signed one.

**Comment by gruyaume** [comment]
> I have squashed the commits now and signature is in place. Please kindly review.

There are still 11 commits in this PR, and 4 of them are not signed:

image

To squash your commits, you can:

```
git reset --soft HEAD~<num of commits>
git commit -S -m <your commit message"
git push --force
```

Here <num of commits> would be `11`, and your commit message can be the same as your PR description `chore: modify product description`.

**Review by gruyaume — CHANGES_REQUESTED** [review]
I added a note on how to squash and sign commits, this is a pre-requisite to merging this.

**Review by markbeierl — APPROVED** [review]

**Comment by solmyrcan** [comment]
Closing this pull request, as PR#16 is the new and clean one.

**Pull request closed without merging**
